### ISSUE TITLE
3 - Backend get methods for /shops and /categories

### ISSUE THREAD

**Issue by KH8** [KH8/stock#5]
GET methods (Backend only) for listing and finding shops and categories should be implemented. 

GET /shops
GET /shops/{:id}
GET /categories
GET /categories/{:id}

**Comment by lukaswajdzik** [comment]
done, review waiting :)

**Comment by KH8** [comment]
Resolved [here](https://github.com/KH8/stock/pull/13) and [here](https://github.com/KH8/stock/pull/14)
